### ISSUE TITLE
Were these submited back upstream? Just out of curiositity, with the 6-year-old repo laying around. 

### ISSUE THREAD

**Issue by ageis** [rosedu/Pidgin#2]

**Comment by flaviusanton** [comment]
Hi,

Oh, wow, it's been quite some time since then. IIRC, there was only one minor patch submitted upstream and that was: https://developer.pidgin.im/ticket/2497.

I was 1st year in college at that time and this was my first contact with open source (and programming in general). Interesting times :).

**Comment by flaviusanton** [comment]
The one with Yahoo Doodle confirmation dialog was _almost_ "working". I remember it was getting a SIGSEGV after some time, so I didn't even try to submit it upstream. Never got back to it to find the problem, though.

**Comment by mihaimaruseac** [comment]
Yeah, no other patches were submitted upstream.
